package com.project.colorinterpreter.utils

object ColorHash {
    private var colorHash : HashMap<String, String?> = HashMap()

    init{
        colorHash["ff826464"] = "0.1 (low cholesterol levels. Healthy condition)"
        colorHash["ff886324"] = "0.2 (low cholesterol levels. Healthy condition)"
        colorHash["ffa8807e"] = "0.3 (low cholesterol levels. Healthy condition)"
        colorHash["ffa88c88"] = "0.4 (low cholesterol levels. Healthy condition)"
        colorHash["ff9d7c75"] = "0.5 (low cholesterol levels. Healthy condition)"
        colorHash["ffa2817c"] = "0.6 (low cholesterol levels. Healthy condition)"
        colorHash["ff988984"] = "0.7 (low cholesterol levels. Healthy condition)"
        colorHash["ff9b8985"] = "0.8 (low cholesterol levels. Healthy condition)"
        colorHash["ff988984"] = "0.9 (low cholesterol levels. Healthy condition)"
        colorHash["ff957d79"] = "1.0 (low cholesterol levels. Healthy condition)"
        colorHash["ff9b6058"] = "1.1 (low cholesterol levels. Healthy condition)"
        colorHash["ff966056"] = "1.2 (low cholesterol levels. Healthy condition)"
        colorHash["ff9b5f54"] = "1.3 (low cholesterol levels. Healthy condition)"
        colorHash["ff9d6a59"] = "1.4 (low cholesterol levels. Healthy condition)"
        colorHash["ff9b6f66"] = "1.5 (low cholesterol levels. Healthy condition)"
        colorHash["ff9ebd5e"] = "1.6 (low cholesterol levels. Healthy condition)"
        colorHash["ff9f665f"] = "1.7 (low cholesterol levels. Healthy condition)"
        colorHash["ff937471"] = "1.8 (low cholesterol levels. Healthy condition)"
        colorHash["ff9a7e7d"] = "1.9 (low cholesterol levels. Healthy condition)"
        colorHash["ff9c7d7b"] = "2.0 (low cholesterol levels. Healthy condition)"
        colorHash["ff94766e"] = "2.1 (low cholesterol levels. Healthy condition)"
        colorHash["ff9e7c70"] = "2.2 (low cholesterol levels. Healthy condition)"
        colorHash["ff96e6a"] = "2.3 (low cholesterol levels. Healthy condition)"
        colorHash["ff987265"] = "2.4 (low cholesterol levels. Healthy condition)"
        colorHash["ff946450"] = "2.5 (low cholesterol levels. Healthy condition)"
        colorHash["ff988682"] = "2.6 (low cholesterol levels. Healthy condition)"
        colorHash["ff948985"] = "2.7 (low cholesterol levels. Healthy condition)"
        colorHash["ff947875"] = "2.8 (low cholesterol levels. Healthy condition)"
        colorHash["ff927f7b"] = "2.9 (low cholesterol levels. Healthy condition)"
        colorHash["ff8055fc"] = "3.0 (low cholesterol levels. Healthy condition)"
        colorHash["ffa37e6b"] = "3.1 (low cholesterol levels. Healthy condition)"
        colorHash["ffa47966"] = "3.2 (low cholesterol levels. Healthy condition)"
        colorHash["ffaea8a8"] = "3.3 (low cholesterol levels. Healthy condition)"
        colorHash["ffa3969"] = "3.4 (low cholesterol levels. Healthy condition)"
        colorHash["ff959190"] = "3.5 (low cholesterol levels. Healthy condition)"
        colorHash["ffa19997"] = "3.6 (low cholesterol levels. Healthy condition)"
        colorHash["ff936d64"] = "3.7 (low cholesterol levels. Healthy condition)"
        colorHash["ff7a7879"] = "3.8 (low cholesterol levels. Healthy condition)"
        colorHash["ffaa827e"] = "3.9 (low cholesterol levels. Healthy condition)"
        colorHash["ff956875"] = "4.0 (low cholesterol levels. Healthy condition)"
        colorHash["ff956f5c"] = "4.1 (low cholesterol levels. Healthy condition)"
        colorHash["ff85675f"] = "4.2 (low cholesterol levels. Healthy condition)"
        colorHash["ff85534c"] = "4.3 (low cholesterol levels. Healthy condition)"
        colorHash["ff946esb"] = "4.4 (low cholesterol levels. Healthy condition)"
        colorHash["ff956d61"] = "4.5 (low cholesterol levels. Healthy condition)"
        colorHash["ff96756e"] = "4.6 (low cholesterol levels. Healthy condition)"
        colorHash["ff976d5d"] = "4.7 (low cholesterol levels. Healthy condition)"
        colorHash["ff8b5247"] = "4.8 (low cholesterol levels. Healthy condition)"
        colorHash["ff8f6360"] = "4.9 (low cholesterol levels. Healthy condition)"
        colorHash["ff895446"] = "5.0 (low cholesterol levels. Healthy condition)"
        colorHash["ff045e56"] = "5.1 (low cholesterol levels. Healthy condition)"
        colorHash["ffa15e58"] = "5.2 (low cholesterol levels. Healthy condition)"
        colorHash["ffa25648"] = "5.3 (High cholesterol level, but within healthy limit)"
        colorHash["ff9a5653"] = "5.4 (High cholesterol level, but within healthy limit)"
        colorHash["ff9b6a6a"] = "5.5 (High cholesterol level, but within healthy limit)"
        colorHash["ff965956"] = "5.6 (High cholesterol level, but within healthy limit)"
        colorHash["ff95b58"] = "5.7 (High cholesterol level, but within healthy limit)"
        colorHash["ff985c5c"] = "5.8 (High cholesterol level, but within healthy limit)"
        colorHash["ff92412c"] = "5.9 (High cholesterol level, but within healthy limit)"
        colorHash["ff9c7b72"] = "6.0 (High cholesterol level, but within healthy limit)"
        colorHash["ff9b6251"] = "6.1 (High cholesterol level, but within healthy limit)"
        colorHash["ff837a7d"] = "6.2 (High cholesterol level, but within healthy limit)"
        colorHash["ffac8a7e"] = "6.3 (High cholesterol levels. High risk. Please see the doctor)"
        colorHash["ffa06047"] = "6.4 (High cholesterol levels. High risk. Please see the doctor)"
        colorHash["ff8f7f80"] = "6.5 (High cholesterol levels. High risk. Please see the doctor)"
        colorHash["ff8e7169"] = "6.6 (High cholesterol levels. High risk. Please see the doctor)"
        colorHash["ffa56a58"] = "6.7 (High cholesterol levels. High risk. Please see the doctor)"
        colorHash["ffa78385"] = "6.8 (High cholesterol levels. High risk. Please see the doctor)"
        colorHash["ff9f6057"] = "6.9 (High cholesterol levels. High risk. Please see the doctor)"
        colorHash["ffa78586"] = "7.0 (High cholesterol levels. High risk. Please see the doctor)"
        colorHash["ffa49898"] = "7.1 (High cholesterol levels. High risk. Please see the doctor)"
        colorHash["ffa3706d"] = "7.2 (High cholesterol levels. High risk. Please see the doctor)"
        colorHash["ff8ebdd64"] = "7.3 (High cholesterol levels. High risk. Please see the doctor)"
        colorHash["ff8dbf64"] = "7.4 (High cholesterol levels. High risk. Please see the doctor)"
        colorHash["ffa58181"] = "7.5 (High cholesterol levels. High risk. Please see the doctor)"
        colorHash["ffaa8c8a"] = "7.6 (High cholesterol levels. High risk. Please see the doctor)"
        colorHash["ffa99d9d"] = "7.7 (High cholesterol levels. High risk. Please see the doctor)"
        colorHash["ffa16a65"] = "7.8 (High cholesterol levels. High risk. Please see the doctor)"
        colorHash["ffa85c52"] = "7.9 (High cholesterol levels. High risk. Please see the doctor)"
        colorHash["ffa45e45"] = "8.0 (High cholesterol levels. High risk. Please see the doctor)"
        colorHash["ffa9b8c5"] = "8.1 (High cholesterol levels. High risk. Please see the doctor)"
        colorHash["ff6e5c58"] = "8.2 (High cholesterol levels. High risk. Please see the doctor)"
        colorHash["ff7e7272"] = "8.3 (High cholesterol levels. High risk. Please see the doctor)"
        colorHash["ff696461"] = "8.4 (High cholesterol levels. High risk. Please see the doctor)"
        colorHash["ff725952"] = "8.5 (High cholesterol levels. High risk. Please see the doctor)"
        colorHash["ff8c7a7a"] = "8.6 (High cholesterol levels. High risk. Please see the doctor)"
        colorHash["ff855d4c"] = "8.7 (High cholesterol levels. High risk. Please see the doctor)"
        colorHash["ff7e5f5bc"] = "8.8 (High cholesterol levels. High risk. Please see the doctor)"
        colorHash["ff9c8782"] = "8.9 (High cholesterol levels. High risk. Please see the doctor)"
        colorHash["ff764e34"] = "9.0 (High cholesterol levels. High risk. Please see the doctor)"
        colorHash["ffa59d9b"] = "9.1 (High cholesterol levels. High risk. Please see the doctor)"
        colorHash["ff96827b"] = "9.2 (High cholesterol levels. High risk. Please see the doctor)"
        colorHash["ffb2b0b1"] = "9.3 (High cholesterol levels. High risk. Please see the doctor)"
        colorHash["ff887274"] = "9.4 (High cholesterol levels. High risk. Please see the doctor)"
        colorHash["ff907268"] = "9.5 (High cholesterol levels. High risk. Please see the doctor)"
        colorHash["ff9f725d"] = "9.6 (High cholesterol levels. High risk. Please see the doctor)"
        colorHash["ffa36f61"] = "9.7 (High cholesterol levels. High risk. Please see the doctor)"
        colorHash["ffa17977"] = "9.8 (High cholesterol levels. High risk. Please see the doctor)"
        colorHash["ffa2685a"] = "9.9 (High cholesterol levels. High risk. Please see the doctor)"
        colorHash["ffa29e9f"] = "10.0 (High cholesterol levels. High risk. Please see the doctor)"

    }

    fun getInformation(hash: String): String? {
        return colorHash[hash]
    }

}